region:
  world: world
  min-x: -500
  max-x: 500
  min-z: -500
  max-z: 500
  min-y: 60

crate:
  lifetime-seconds: 20
  allow-multiple-worlds: false
  texture: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYjJjYTk3YzRjZjE5YjU0YjE3MDZhYzk1Zjc5ZmEyODQ5ZmZkZGIwZjYzMDllNzBmZDJkMjQ3MTgwMTYxYmI1NyJ9fX0="
  spawn-times:
    - "20:00"
    - "23:15"
  amount: 5

rewards:
  - "eventpoints:20"
  - "item:DIAMOND:1"

messages:
  start: "§aCrate telah muncul di {x} {y} {z}!"
  half: "§6Crate akan hilang dalam {time} detik!"
  expired: "§cCrate hilang karena tidak diklaim!"
  claimed: "§b{player} §7telah mengklaim crate!"