region:
  world: world
  min-x: -500
  max-x: 500
  min-z: -500
  max-z: 500
  min-y: 60

crate:
  lifetime-seconds: 20
  allow-multiple-worlds: false
  texture: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYzE4MDMxNThjY2VlY2QyMjY4YTBhYTZmNTU2ZjYxMGY1ZjRhMWMzYzI2NDM1NTk3Njg0OGU0YTE5ZjQwMmMzZCJ9fX0="
  spawn-times:
    - "20:00"
    - "23:15"
  amount: 3

rewards:
  - "eventpoints:20"
  - "item:DIAMOND:1"
  - "command:say %player% got lucky!"

messages:
  start: "§aCrate telah muncul di {x} {y} {z}!"
  half: "§6Crate akan hilang dalam {time} detik!"
  expired: "§cCrate hilang karena tidak diklaim!"
  claimed: "§b{player} §7telah mengklaim crate!"